# Generated by Django 5.1.3 on 2024-11-29 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usr',
            fields=[
                ('user_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('fname', models.CharField(max_length=50)),
                ('mname', models.CharField(max_length=50, null=True)),
                ('lname', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=100, null=True)),
                ('country', models.CharField(max_length=100, null=True)),
                ('postal_code', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
