# Generated by Django 4.2.16 on 2024-11-30 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('airline_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('country_of_origin', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('registration_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('airplane_type', models.CharField(max_length=30, null=True)),
                ('baggage_capacity', models.IntegerField()),
                ('current_payload', models.IntegerField()),
                ('coordinates', models.CharField(max_length=20, null=True)),
                ('airline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.airline')),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('code', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('airport_name', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=50, null=True)),
                ('city', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Baggage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracker_id', models.CharField(max_length=100)),
                ('tracker_type', models.CharField(max_length=20, null=True)),
                ('is_time_sensitive', models.BooleanField()),
                ('is_hazardous', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('passport_no', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('country_citizenship', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.usr')),
                ('employee_role', models.CharField(max_length=50, null=True)),
                ('airline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.airline')),
            ],
        ),
        migrations.CreateModel(
            name='FlightLeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_id', models.CharField(max_length=20)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('airplane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.airplane')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_airport', to='api.airport')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_airport', to='api.airport')),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('incident_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('is_damaged', models.BooleanField()),
                ('is_lost', models.BooleanField()),
                ('is_delayed', models.BooleanField()),
                ('incident_time', models.DateTimeField()),
                ('incident_resolved', models.BooleanField()),
                ('incident_description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(max_length=100)),
                ('passport_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Loc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=100)),
                ('coordinates', models.CharField(max_length=20)),
            ],
            options={
                'unique_together': {('location_name', 'coordinates')},
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('notification_content', models.TextField()),
                ('notification_time', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='usr',
            name='user_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='NotificationSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.notification')),
                ('tracker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.baggage')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationSent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.notification')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usr')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
            ],
        ),
        migrations.CreateModel(
            name='LocationUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField()),
                ('location_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.loc')),
                ('tracker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.baggage')),
            ],
        ),
        migrations.CreateModel(
            name='ItineraryFlights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.itinerary')),
                ('flight_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.flightleg')),
            ],
        ),
        migrations.CreateModel(
            name='IncidentEmployees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.incident')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
            ],
        ),
        migrations.AddField(
            model_name='incident',
            name='incident_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.loc'),
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.usr'),
        ),
        migrations.CreateModel(
            name='BaggageCarousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carousel_number', models.CharField(max_length=100)),
                ('coordinates', models.CharField(max_length=20)),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.airport')),
            ],
        ),
        migrations.AddField(
            model_name='baggage',
            name='booking_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.itinerary'),
        ),
        migrations.AddField(
            model_name='baggage',
            name='passport_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customer'),
        ),
        migrations.AddField(
            model_name='airplane',
            name='destination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_airplanes', to='api.airport'),
        ),
        migrations.CreateModel(
            name='StorageFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=100)),
                ('coordinates', models.CharField(max_length=20)),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.airport')),
            ],
            options={
                'unique_together': {('location_name', 'airport')},
            },
        ),
        migrations.CreateModel(
            name='SecurityCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=100)),
                ('coordinates', models.CharField(max_length=20)),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.airport')),
            ],
            options={
                'unique_together': {('location_name', 'airport')},
            },
        ),
        migrations.CreateModel(
            name='PhoneNumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usr')),
            ],
            options={
                'unique_together': {('user', 'phone_no')},
            },
        ),
        migrations.AddConstraint(
            model_name='notificationsubject',
            constraint=models.UniqueConstraint(fields=('notification_id', 'tracker_id'), name='unique_notification_tracker'),
        ),
        migrations.AlterUniqueTogether(
            name='notificationsent',
            unique_together={('notification', 'recipient')},
        ),
        migrations.AddConstraint(
            model_name='locationupdate',
            constraint=models.UniqueConstraint(fields=('update_time', 'tracker_id'), name='unique_update_time_tracker'),
        ),
        migrations.AddConstraint(
            model_name='itineraryflights',
            constraint=models.UniqueConstraint(fields=('booking_id', 'flight_id'), name='unique_booking_flight'),
        ),
        migrations.AddConstraint(
            model_name='itinerary',
            constraint=models.UniqueConstraint(fields=('booking_id', 'passport_no'), name='unique_booking_passport'),
        ),
        migrations.AlterUniqueTogether(
            name='incidentemployees',
            unique_together={('incident', 'user')},
        ),
        migrations.AddConstraint(
            model_name='flightleg',
            constraint=models.UniqueConstraint(fields=('flight_id', 'airplane', 'origin', 'destination'), name='unique_flight_leg'),
        ),
        migrations.AlterUniqueTogether(
            name='baggagecarousel',
            unique_together={('carousel_number', 'airport')},
        ),
        migrations.AddConstraint(
            model_name='baggage',
            constraint=models.UniqueConstraint(fields=('tracker_id', 'passport_no'), name='unique_tracker_passport'),
        ),
    ]
