# Generated by Django 4.2.16 on 2024-11-30 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_airline_airplane_airport_baggage_customer_employee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airplane',
            name='destination',
        ),
    ]
