# Generated by Django 5.1.3 on 2024-12-01 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_airplane_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='baggage',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='airplane',
            name='baggage_capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='airplane',
            name='current_payload',
            field=models.IntegerField(default=0),
        ),
    ]
