# Generated by Django 5.1.3 on 2024-12-01 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_baggage_weight_alter_airplane_baggage_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_executive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
